# Generated by Django 2.1.7 on 2019-08-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transpose', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('video_name', models.CharField(max_length=80)),
                ('original_file', models.FileField(upload_to='audio/')),
                ('transposed_file', models.FileField(upload_to='shifted_audio/')),
            ],
        ),
        migrations.DeleteModel(
            name='YtURL',
        ),
    ]
